#!/usr/bin/env python3
import json, urllib.request, os, sys, subprocess

TOKEN = os.environ["GITHUB_TOKEN"]
REPO = os.environ.get("GITHUB_REPOSITORY", "WEAndroidDevTeam/Listify")
TICKET = os.environ.get("JIRA_TICKET", "LIS-AUTO")
CRASH_TITLE = os.environ.get("CRASH_TITLE", "Unknown crash")

try:
    result = json.load(open("/tmp/fix_result.json"))
except Exception as e:
    print(f"No fix_result.json: {e}", file=sys.stderr)
    result = {"root_cause": "Analysis unavailable", "fix_description": "Manual investigation required",
              "confidence": "low", "affected_file": "", "fixed_code": ""}

root_cause = result.get("root_cause", "")
fix_desc = result.get("fix_description", "")
confidence = result.get("confidence", "low")
affected_file = result.get("affected_file", "")
commit_msg = result.get("commit_message", f"fix: address {CRASH_TITLE[:50]}")

branch = f"autofix/{TICKET.lower()}-crash-fix"

subprocess.run(["git", "config", "user.email", "autofix@listify.ai"])
subprocess.run(["git", "config", "user.name", "Listify AutoFix Bot"])

# Create branch
r = subprocess.run(["git", "checkout", "-b", branch], capture_output=True, text=True)
print(f"Branch checkout: {r.stdout} {r.stderr}")

# Always create an analysis doc (safe — never overwrites real code unless high confidence)
os.makedirs("docs", exist_ok=True)
analysis_path = f"docs/crash_analysis_{TICKET}.md"
with open(analysis_path, "w") as f:
    f.write(f"# Crash Analysis: {TICKET}\n\n")
    f.write(f"## Crash\n{CRASH_TITLE}\n\n")
    f.write(f"## Root Cause\n{root_cause}\n\n")
    f.write(f"## Suggested Fix\n{fix_desc}\n\n")
    f.write(f"## Confidence\n{confidence}\n\n")
    f.write(f"## Affected File\n{affected_file or 'Unknown'}\n")
subprocess.run(["git", "add", analysis_path])
subprocess.run(["git", "commit", "-m", f"{commit_msg}\n\nAuto-generated analysis for {TICKET}"])

# Push using token in URL
repo_url = f"https://x-access-token:{TOKEN}@github.com/{REPO}.git"
subprocess.run(["git", "remote", "set-url", "origin", repo_url])
push = subprocess.run(["git", "push", "origin", branch], capture_output=True, text=True)
print(f"Push: {push.stdout} {push.stderr}")

# Open PR
pr_body = f"""## Auto-Fix Analysis: {TICKET}

**Root Cause:** {root_cause}

**Suggested Fix:** {fix_desc}

**Confidence:** {confidence.upper()}

**Affected File:** {affected_file or 'Unknown'}

---
This PR was auto-generated by the Listify crash analyzer pipeline.
Review the analysis in `docs/crash_analysis_{TICKET}.md` and apply the fix.
Auto-fix PRs are NEVER auto-merged.

Fixes {TICKET}"""

pr_data = json.dumps({
    "title": f"[AutoFix] {TICKET}: {CRASH_TITLE[:60]}",
    "body": pr_body,
    "head": branch,
    "base": "main"
}).encode()

req = urllib.request.Request(
    f"https://api.github.com/repos/{REPO}/pulls",
    data=pr_data, method="POST",
    headers={
        "Authorization": f"token {TOKEN}",
        "Accept": "application/vnd.github+json",
        "Content-Type": "application/json"
    }
)
try:
    with urllib.request.urlopen(req) as r:
        pr = json.loads(r.read())
        pr_url = pr.get("html_url", "")
        print(f"PR created: {pr_url}")
        with open("/tmp/pr_url.txt", "w") as f:
            f.write(pr_url)
except urllib.error.HTTPError as e:
    err = e.read().decode()
    print(f"PR creation failed {e.code}: {err}", file=sys.stderr)
    with open("/tmp/pr_url.txt", "w") as f:
        f.write(f"PR creation failed: {e.code}")
