#!/usr/bin/env python3
import json, urllib.request, os, sys, subprocess

TOKEN = os.environ["GITHUB_TOKEN"]
REPO = os.environ.get("GITHUB_REPOSITORY", "WEAndroidDevTeam/Listify")
TICKET = os.environ.get("JIRA_TICKET", "LIS-AUTO")
CRASH_TITLE = os.environ.get("CRASH_TITLE", "Unknown crash")

result = {}
try:
    result = json.load(open("/tmp/fix_result.json"))
except:
    result = {"root_cause": "Analysis unavailable", "fix_description": "Manual investigation required",
              "confidence": "low", "affected_file": "", "fixed_code": ""}

root_cause = result.get("root_cause", "")
fix_desc = result.get("fix_description", "")
confidence = result.get("confidence", "low")
affected_file = result.get("affected_file", "")
fixed_code = result.get("fixed_code", "")
commit_msg = result.get("commit_message", f"fix: address {CRASH_TITLE[:50]}")

branch = f"autofix/{TICKET.lower()}-crash-fix"

subprocess.run(["git", "config", "user.email", "autofix@listify.ai"])
subprocess.run(["git", "config", "user.name", "Listify AutoFix Bot"])
subprocess.run(["git", "checkout", "-b", branch])

if affected_file and os.path.exists(affected_file) and fixed_code and confidence == "high":
    with open(affected_file, "w") as f:
        f.write(fixed_code)
    subprocess.run(["git", "add", affected_file])
else:
    analysis_path = f"docs/crash_analysis_{TICKET}.md"
    with open(analysis_path, "w") as f:
        f.write(f"# Crash Analysis: {TICKET}\n\n## Root Cause\n{root_cause}\n\n## Suggested Fix\n{fix_desc}\n\n## Affected File\n{affected_file or 'Unknown'}\n")
    subprocess.run(["git", "add", analysis_path])

subprocess.run(["git", "commit", "-m", f"{commit_msg}\n\nAuto-generated for {TICKET}"])

repo_url = f"https://x-access-token:{TOKEN}@github.com/{REPO}.git"
subprocess.run(["git", "remote", "set-url", "origin", repo_url])
subprocess.run(["git", "push", "origin", branch])

confidence_emoji = {"high": "GREEN", "medium": "YELLOW", "low": "RED"}.get(confidence, "GREY")
pr_body = f"""## Auto-Fix: {TICKET}

Root Cause: {root_cause}

Fix: {fix_desc}

Confidence: {confidence_emoji} {confidence.upper()}

Affected File: {affected_file or 'Unknown'}

Review Checklist:
- Root cause analysis is correct
- Fix does not introduce regressions
- Unit test added to prevent recurrence
- CI passes

This PR was auto-generated by the Listify crash analyzer. Review carefully before merging.
Auto-fix PRs are NEVER auto-merged.

Fixes {TICKET}"""

pr_data = json.dumps({
    "title": f"[AutoFix] {TICKET}: {CRASH_TITLE[:60]}",
    "body": pr_body,
    "head": branch,
    "base": "main"
}).encode()

req = urllib.request.Request(
    f"https://api.github.com/repos/{REPO}/pulls",
    data=pr_data, method="POST",
    headers={
        "Authorization": f"token {TOKEN}",
        "Accept": "application/vnd.github+json",
        "Content-Type": "application/json"
    }
)
try:
    with urllib.request.urlopen(req) as r:
        pr = json.loads(r.read())
        pr_url = pr.get("html_url", "")
        print(f"PR created: {pr_url}")
        with open("/tmp/pr_url.txt", "w") as f:
            f.write(pr_url)
except Exception as e:
    print(f"PR creation failed: {e}", file=sys.stderr)
