#!/usr/bin/env python3
"""
Listify pipeline utilities.
Used by GitHub Actions and local automation to open PRs with review checklists.
"""
import json, subprocess, sys, urllib.request, urllib.error

def open_pr(token, repo, head_branch, base_branch, title, body):
    """Open a PR and return (pr_number, pr_url). Raises on failure."""
    payload = json.dumps({
        "title": title,
        "body": body,
        "head": head_branch,
        "base": base_branch
    }).encode()
    req = urllib.request.Request(
        f"https://api.github.com/repos/{repo}/pulls",
        data=payload,
        method="POST",
        headers={
            "Authorization": f"token {token}",
            "Accept": "application/vnd.github+json",
            "Content-Type": "application/json"
        }
    )
    with urllib.request.urlopen(req) as r:
        data = json.loads(r.read())
    return data["number"], data["html_url"]


def request_reviewers(token, repo, pr_number, reviewers):
    """Request code review from a list of GitHub usernames."""
    payload = json.dumps({"reviewers": reviewers}).encode()
    req = urllib.request.Request(
        f"https://api.github.com/repos/{repo}/pulls/{pr_number}/requested_reviewers",
        data=payload,
        method="POST",
        headers={
            "Authorization": f"token {token}",
            "Accept": "application/vnd.github+json",
            "Content-Type": "application/json"
        }
    )
    with urllib.request.urlopen(req) as r:
        return r.status


def add_labels(token, repo, pr_number, labels):
    """Add labels to a PR."""
    payload = json.dumps({"labels": labels}).encode()
    req = urllib.request.Request(
        f"https://api.github.com/repos/{repo}/issues/{pr_number}/labels",
        data=payload,
        method="POST",
        headers={
            "Authorization": f"token {token}",
            "Accept": "application/vnd.github+json",
            "Content-Type": "application/json"
        }
    )
    with urllib.request.urlopen(req) as r:
        return r.status


def build_feature_pr_body(ticket, branch, changes, acceptance_criteria, test_notes):
    """Generate a standardised PR description for feature tickets."""
    return f"""## Summary
Implements [{ticket}](https://androiddevteam.atlassian.net/browse/{ticket}).

## Changes
{changes}

## Acceptance Criteria
{acceptance_criteria}

## Testing
{test_notes}

## Review Checklist
- [ ] Code follows project architecture (MVVM + Clean Architecture)
- [ ] No hardcoded strings — all in `strings.xml`
- [ ] Unit tests added / updated for new logic
- [ ] No TODOs left in code
- [ ] CI passes (lint + tests + build)

---
*Auto-generated by Listify CI pipeline. Requires 1 approval + CI green before merge.*

Closes {ticket}"""


def build_autofix_pr_body(ticket, root_cause, fix_description, confidence, affected_file):
    """Generate a PR description for auto-fix tickets."""
    confidence_emoji = {"high": "🟢", "medium": "🟡", "low": "🔴"}.get(confidence, "⚪")
    return f"""## 🤖 Auto-Fix: {ticket}

**Root Cause:** {root_cause}

**Fix:** {fix_description}

**Confidence:** {confidence_emoji} {confidence.upper()}

**Affected File:** `{affected_file}`

## Review Checklist
- [ ] Root cause analysis is correct
- [ ] Fix doesn't introduce regressions
- [ ] Unit test added to prevent recurrence
- [ ] CI passes

> ⚠️ **This PR was auto-generated by Claude AI. Review carefully before merging.**
> Auto-fix PRs are NEVER auto-merged regardless of confidence level.

Fixes {ticket}"""
